apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-git
  namespace: tnguyen138-dev
  labels:
    app: openshift-git
    app.kubernetes.io/name: openshift-git
    app.kubernetes.io/instance: openshift-git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-git
  template:
    metadata:
      labels:
        app: openshift-git
        app.kubernetes.io/name: openshift-git
        app.kubernetes.io/instance: openshift-git
    spec:
      containers:
        - name: openshift-git
          image: image-registry.openshift-image-registry.svc:5000/tnguyen138-dev/openshift-git:latest
          ports:
            - containerPort: 8080